### ISSUE TITLE
Guide for install 

### ISSUE THREAD

**Issue by graceyangfan** [zhenpingfeng/burgerflipper#1]
Hello, would you like to add some steps for how to install this  libary

**Comment by zhenpingfeng** [comment]
git clone the API library "exrs", put it to the path ```../``` , then ```RUST_LOG=info cargo run config.json```

**Comment by zhenpingfeng** [comment]
https://github.com/zhenpingfeng/burgerflipper/commit/be6f9cbb582ca29c607966a9acac0fcbbff7d336 and 
https://github.com/zhenpingfeng/exrs/commit/e194a04ec631f42eaa68981a6321b7f8585224eb should be fix this issue, use ```RUST_LOG=info cargo run --release --bin burgerfilpper config.json
``` to run the program.

**Comment by graceyangfan** [comment]
@zhenpingfeng  thanks,it works now
