### ISSUE TITLE
Maybe place Order with only maker 

### ISSUE THREAD

**Issue by graceyangfan** [zhenpingfeng/burgerflipper#2]
Thanks for your great project!I have a test on bianace,the win money do not cover the commision,place order with only maker can reduce the commision

**Comment by zhenpingfeng** [comment]
if you got a market order means your network latency is too high. this project tick to trade is under sub-millisecond. my server to ping binance server is about 300us, call fapi.binance.com/ping API can return about 1.2ms.

**Comment by graceyangfan** [comment]
tanks for your reply，I did not meet market order，almost all orders are filled with limited order

**Comment by graceyangfan** [comment]
tanks for your reply,I did not meet market order,almost all orders are filled with limited order,but the order is filled as a taker not a maker, ustd maker commission is half of taker in binance, while busd maker commission is negative

**Comment by zhenpingfeng** [comment]
https://github.com/zhenpingfeng/burgerflipper/commit/b55a54987237692e1facb97f11be03decf7c2ca7
should be good now.

**Comment by graceyangfan** [comment]
@zhenpingfeng  I am not familiar to Rust lauguage,but the binance send order API can set `post_only=True` to make sure limited order filled as a maker

**Comment by zhenpingfeng** [comment]
Yep, TimeInForce::GTX is Post-only mode. [GTX - Good Till Crossing (Post Only)](https://binance-docs.github.io/apidocs/futures/en/#public-endpoints-info)

**Comment by graceyangfan** [comment]
@zhenpingfeng  Thanks a lot!
