### ISSUE TITLE
pls halp, how do I delete the app?

### ISSUE THREAD

**Issue by wassname** [zhenpingfeng/burgerflipper#3]
This code worked well. For a while I was smoothly increasing my savings. 

So I added my wife's savings, and her boyfriends'.

But now it's all gone to -inf. [Here is a video description of the problem](https://www.youtube.com/watch?v=61Q6wWu5ziY).

Now my hands are greasy and callused from working behind wendies. 

I would like to delete the app now, but cannot find the button. Can you debug the problem?

**Comment by zhenpingfeng** [comment]
The delete key should be on the keyboard, look for it with your eyes wide open.  But I suggest you join us  @McDonald's to flip the burger first.

**Comment by zhenpingfeng** [comment]
BTW In your experience how does the point process kind of model work on hft?  I see a lot of people doing research on them. Is it worth trying?

**Comment by zhenpingfeng** [comment]
![photo_2022-10-04_23-00-06](https://user-images.githubusercontent.com/13215166/193854359-e70c2f35-4c65-4dbe-af89-a11c05f54dc6.jpg)
After aggregating liquidity across multiple exchanges, it will be easy to see that large traders periodically consume liquidity on a particular exchange, and this kind cyclical features should fit well with the point process model, then a twap hunter should can be make.

**Comment by wassname** [comment]
> BTW In your experience how does the point process kind of model work on hft? I see a lot of people doing research on them. Is it worth trying?

Yeah that sounds like it might work. Machine learning models struggle with financial series in general, with off-the-shelf models just not working. But if there is strong cyclicity like that then I think there's a good chance it can pick it up and predict it well.

I would start with models that either work well everywhere (that are used as benchmarks in papers) or ones that have specifically been testing on hard financial series (quite uncommon). Most quant ml papers are just rubbish that wont replicate or don't include fees (in my experience)!

I like this one generic timeseries model but it's a bit complex https://github.com/timeseriesAI/tsai/blob/main/tsai/models/InceptionTimePlus.py

So you might want to try this nice and simple model, and just put in a custom period is needed https://github.com/facebook/prophet

Bear in mind I haven't made any money from my models, so I'm probably over complicating things ;)

**Comment by wassname** [comment]
I saw you liked Autoformer. I think the AutoFormer, FEDFormer, and DeepTIMe model look promising, since they are benchmarked on financial timeseries. I'm giving them a try now and they are tricky to get working. Have you had a go?

I tried some of these custom loss functions tho, and they seem to give just terrible gradients https://github.com/zhenpingfeng/Adjusted-MAE-loss-function

Machine learning, it's a total mess!

**Comment by zhenpingfeng** [comment]
you should try the MSE version, that MAE version will cause gradient explosion. the loss idea is predict return is hard but we can more focus on predicting up or down.

**Comment by wassname** [comment]
OK I'll give it a try! Yeah I've had much much better results with just classifying as up (more than the fee), or down (more than the fee).

I had one promising result where I classified down [outlier, down (more than fee), sideways, up (more than fee), up (outlier)].

**Comment by wassname** [comment]
BTW this is deeptime https://github.com/salesforce/DeepTIMe, it's a successor to autoformer and is testing on some exchange and weather data

**Comment by zhenpingfeng** [comment]
yep, i also findout that using classifier can get good result more than regression in Jane Street Market Prediction https://www.kaggle.com/competitions/jane-street-market-prediction/. Maybe it's because the ‘return’ itself is too noisy for model.

**Comment by wassname** [comment]
Is it AdjMSELoss2 that you like? That's the one that did best in the paper

**Comment by zhenpingfeng** [comment]
yes

**Comment by wassname** [comment]
chatting about this kind of stuff if fun, if you have time of from McD's you can find me on discord wassname#1892, or email wassname first part, and last part: wassname.org

I'll delete this post after a couple of days to avoid spam

**Comment by zhenpingfeng** [comment]
okay, but ur discord account not accepting friend requests.

**Comment by wassname** [comment]
ops, DM's open now
